### ISSUE TITLE
Crash Triggered by Pasting Renamed Subtree into New Tree

### ISSUE THREAD

**Issue by moccajoghurt** [BehaviorTree/Groot2#29] opened 2023-09-08 11:26 UTC
**To Reproduce**

1. Create a Subtree: Start by creating a new subtree.
2. Integrate Subtree: Add the newly created subtree to another tree.
3. Rename the Subtree: Change the name of the original subtree.
4. Copy the Integrated Subtree: Go to the tree where you added the subtree (before renaming) and copy it.
5. Paste into a New Tree: Paste the copied subtree into a different tree.
6. Result: Groot2 crashes.

The bug arises due to the subtree's ID not being updated within the tree where it's utilized. Manually updating the ID serves as a temporary solution to this issue.

**Comment by facontidavide** [comment] 2023-09-08 11:32
Thanks a lot. I will address that ASAP and prepare a new release the next week!

**Comment by facontidavide** [comment] 2023-09-08 11:46
I tried to replicate the steps you described but could not reproduce the issue (found a different one, tough)

See video


https://github.com/BehaviorTree/Groot2/assets/2822888/91e36a60-c184-4ac0-90b1-1854fe1c77ab

**Comment by moccajoghurt** [comment] 2023-09-08 12:11
I omitted mentioning that a port remapping must be added to the created subtree in my initial description. Below is the revised explanation:

1. Create a Subtree: Begin by crafting a new subtree.
2. Integrate Subtree: Incorporate the newly created subtree into another tree.
3. Add Port Remapping: Apply a port remapping to the created subtree.
4. Rename the Subtree: Modify the original subtree's name.
5. Result: Groot2 crashes upon renaming.

https://github.com/BehaviorTree/Groot2/assets/2771765/50e46f32-c74a-4b45-944c-c4bb85a579cf


I currently cannot reproduce my original bug report because now the crash occurs earlier.

**Comment by facontidavide** [comment] 2023-09-08 12:21
thanks. Now it is clear. As I said, I will fix it as soon as I can!
Just to be sure, are you using the PRO or free version?

**Comment by moccajoghurt** [comment] 2023-09-08 12:22
I am using the free version.

**Comment by facontidavide** [comment] 2023-09-11 10:05
fixed in 1.2.0

**Closed as completed by facontidavide** 2023-09-11 10:05 UTC
Labels: bug
